### DISCUSSION TITLE
Digital Zoom from Webcam

### DISCUSSION THREAD

**Discussion by sckowalski** [photobooth-app/photobooth-app#449] [Q&A]
I've been experimenting with a few different webcam options for my photobooth and some of my planned installations take a photo from a longer distance.

I'm currently using V4L2 as my backend and any attempts to use zoom using the CLI haven't worked.

I have also tried modifying the zoom using the `private.css` file and the `#overlay-image` to no success.

Any suggestions on what to try next?

Thanks!

**Comment by mgineer85** [comment]
Hi,

I just tried and put 
```css
#overlay-image {
  transform: scale(1.5); /* default: 1.0 to apply no zoom. 1.5 zooms in, smaller values than 1.0 usually make no sense */
}
```
in userdata/private.css file and it worked. can you describe more in detail how you do it?
